begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(18);
select has_table('public','quote_request_quotation_email_orchestrations','quotation email evidence exists');
select has_function('public','prepare_issued_quotation_delivery_with_capability_v1',array['uuid','text','text','timestamp with time zone','uuid','uuid','text','text'],'atomic delivery preparation exists');
select has_function('public','prepare_quotation_acceptance_confirmation_v1',array['uuid','text','text','uuid','text','text'],'confirmation preparation exists');
select ok(not has_function_privilege('anon','public.prepare_issued_quotation_delivery_with_capability_v1(uuid,text,text,timestamp with time zone,uuid,uuid,text,text)','execute'),'anon cannot prepare delivery');
select ok(not has_function_privilege('authenticated','public.prepare_quotation_acceptance_confirmation_v1(uuid,text,text,uuid,text,text)','execute'),'authenticated cannot prepare confirmation');
select ok(has_function_privilege('service_role','public.prepare_issued_quotation_delivery_with_capability_v1(uuid,text,text,timestamp with time zone,uuid,uuid,text,text)','execute'),'service role can prepare delivery');
select ok(has_function_privilege('service_role','public.prepare_quotation_acceptance_confirmation_v1(uuid,text,text,uuid,text,text)','execute'),'service role can prepare confirmation');
select ok(not has_table_privilege('service_role','public.quote_request_quotation_email_orchestrations','insert'),'service role cannot forge orchestration evidence');
select ok(not has_table_privilege('service_role','public.quote_request_quotation_email_orchestrations','update'),'service role cannot update orchestration evidence');
select ok(not has_table_privilege('service_role','public.quote_request_quotation_email_orchestrations','delete'),'service role cannot delete orchestration evidence');
select is((select count(*)::integer from public.quote_request_quotation_email_orchestrations),0,'migration creates no delivery evidence');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name='quote_request_quotation_email_orchestrations' and column_name~'(token|secret|html|text|body|attachment)'),'evidence stores no plaintext token or message body');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='quotation_delivery_email_once_per_version'),'delivery once-per-version index exists');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='quotation_acceptance_email_once_per_version'),'confirmation once-per-version index exists');
select is((select count(*)::integer from pg_enum join pg_type on pg_type.oid=enumtypid where typname='quote_request_email_kind' and enumlabel in('quotation_delivery','quotation_acceptance_customer','quotation_acceptance_internal')),3,'three quotation email job kinds exist');
select is((select count(*)::integer from information_schema.tables where table_schema='public' and table_name like '%invoice%' and table_name like '%email%'),0,'quotation email authority creates no invoice table');
select throws_ok($$select * from public.prepare_quotation_acceptance_confirmation_v1('00000000-0000-4000-8000-000000000001','ACCEPTANCE_CONFIRMATION_CUSTOMER','ACCEPTANCE_CONFIRMATION_CUSTOMER_NL_BE_v1','d3e10000-0000-4000-8000-000000000001','test',null)$$,'P0001','ACCEPTANCE_NOT_FOUND','confirmation requires existing acceptance');
select is((select count(*)::integer from public.quote_request_email_jobs where kind in('quotation_delivery','quotation_acceptance_customer','quotation_acceptance_internal')),0,'failed preparation creates no job side effect');
select * from finish();
rollback;
