begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(27);
select has_table('public','quote_request_quotation_acceptance_capabilities','capability authority exists');
select has_table('public','quote_request_quotation_acceptance_capability_events','capability event log exists');
select has_table('public','quote_request_quotation_acceptance_capability_operations','capability operation ledger exists');
select has_function('public','create_quotation_acceptance_capability_v1',array['uuid','text','timestamp with time zone','uuid','text','text'],'trusted create RPC exists');
select has_function('public','resolve_quotation_acceptance_capability_v1',array['text'],'safe resolver exists');
select has_function('public','submit_quotation_acceptance_capability_v1',array['text','text','text','text','text','text','text','boolean','uuid'],'public orchestration RPC exists');
select has_function('public','revoke_quotation_acceptance_capability_v1',array['uuid','text','text','uuid','text'],'trusted revoke RPC exists');
select ok(not has_function_privilege('anon','public.create_quotation_acceptance_capability_v1(uuid,text,timestamp with time zone,uuid,text,text)','execute'),'anon cannot create capability');
select ok(not has_function_privilege('anon','public.submit_quotation_acceptance_capability_v1(text,text,text,text,text,text,text,boolean,uuid)','execute'),'anon cannot call DB submit directly');
select ok(not has_function_privilege('authenticated','public.resolve_quotation_acceptance_capability_v1(text)','execute'),'authenticated cannot call DB resolver directly');
select ok(has_function_privilege('service_role','public.resolve_quotation_acceptance_capability_v1(text)','execute'),'service role can resolve capability');
select ok(not has_table_privilege('service_role','public.quote_request_quotation_acceptance_capabilities','insert'),'service role cannot insert capabilities directly');
select ok(not has_table_privilege('service_role','public.quote_request_quotation_acceptance_capabilities','update'),'service role cannot update capabilities directly');
select ok(not has_table_privilege('service_role','public.quote_request_quotation_acceptance_capabilities','delete'),'service role cannot delete capabilities directly');
select is((select count(*)::integer from public.quote_request_quotation_acceptance_capabilities),0,'migration creates no capability');
select is((public.resolve_quotation_acceptance_capability_v1(repeat('0',64))->>'state'),'INVALID_OR_EXPIRED_LINK','unknown digest returns minimal invalid state');
select is((public.resolve_quotation_acceptance_capability_v1('bad')->>'state'),'INVALID_OR_EXPIRED_LINK','malformed digest returns minimal invalid state');
select is((public.submit_quotation_acceptance_capability_v1(repeat('0',64),'terms','1','Name','name@example.test',null,null,true,'d3e99000-0000-4000-8000-000000000001')->>'state'),'INVALID_OR_EXPIRED_LINK','unknown token cannot submit');
select ok(public.consume_acceptance_capability_rate_limit_v1(repeat('a',64),2),'first capability request is allowed');
select ok(public.consume_acceptance_capability_rate_limit_v1(repeat('a',64),2),'second shared capability request is allowed');
select ok(not public.consume_acceptance_capability_rate_limit_v1(repeat('a',64),2),'shared per-token limit rejects excess requests');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name='quote_request_quotation_acceptance_capabilities' and column_name in('token','raw_token','plaintext_token')),'plaintext token column does not exist');
select is((select count(*)::integer from public.quote_request_quotation_acceptance_capability_events where evidence::text ~ 'token|admin_access_token_hash|service_role'),0,'event log contains no token or internal credential');
select throws_ok($$insert into public.quote_request_quotation_acceptance_capabilities(issuance_id,token_digest,capability_version,status,expires_at,created_by) values('00000000-0000-4000-8000-000000000001',repeat('a',64),1,'ACTIVE',clock_timestamp()+interval '1 day','test')$$,'23503',null,'direct orphan capability insert is rejected by FK');
select ok(not has_function_privilege('anon','public.accept_quotation_v1(uuid,integer,text,text,text,text,text,text,text,boolean,uuid,text)','execute'),'anon still cannot bypass capability into D3E8');
select is((select count(*)::integer from information_schema.tables where table_schema='public' and table_name like '%invoice%' and table_name like '%capability%'),0,'capability has no invoice coupling');
select is((select count(*)::integer from public.quote_request_quotation_acceptance_capability_operations),0,'migration creates no capability operations');
select * from finish();rollback;
