project_id = "xcsptvntvrizwhskaphr"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[functions.submit-quote-request]
verify_jwt = false

[functions.review-quote-request]
verify_jwt = false
